### ISSUE TITLE
我该如何关闭message呢？

### ISSUE THREAD

**Issue by H0nGzA1** [KURANADO2/hammerspoon-kuranado#12]
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/21973212/169089878-65d647d8-e494-434f-8870-d96f1a4099f0.png">
这个快捷键回显我并不需要，我只能手动去掉message吗，没有总开关设置？

**Comment by ceylog** [comment]
@H0nGzA1 可以试试加上这个配置项`hs.hotkey.alertDuration = 0` 可以禁用全局的快捷键alert消息   应该可以解决你的问题  不用每个地方都修改  不然快捷键列表查看那里没有说明   已经提交pr看看作者接不接受

**Comment by KURANADO2** [comment]
@ceylog 已合并，感谢提供代码！
