### ISSUE TITLE
输入法切换问题

### ISSUE THREAD

**Issue by evi1hack** [KURANADO2/hammerspoon-kuranado#13]
### 修改了配置项：
```
local INPUT_CHINESE = 'com.sogou.inputmethod.pinyin'
local INPUT_ABC = 'com.apple.keylayout.ABC'
```

> 搜狗输入法 切换到 ABC 是正常的， 从ABC切换到 搜狗输入法 就不行了。

### 截图
<img width="1129" alt="Snipaste_2022-06-25_20-26-45的副本" src="https://user-images.githubusercontent.com/16398717/175773545-70dfa710-43c0-4e90-8854-4b86502a54b5.png">

<img width="822" alt="Snipaste_2022-06-25_20-32-12" src="https://user-images.githubusercontent.com/16398717/175773669-19c2c1a5-9556-4ef2-bdd8-6c07a42b6d71.png">

**Comment by KURANADO2** [comment]
搜狗输入法的 sourceId 为 `com.sogou.inputmethod.sogou.pinyin`

获取输入法 sourceId 的方法为：

右键点击菜单栏 Hammerspoon 锤子 -> console，打开 Hammerspoon 控制台，输入如下命令

```
hs.keycodes.currentSourceID()
```

<img width="435" alt="image" src="https://user-images.githubusercontent.com/20608930/175775064-090c0852-872e-4e14-8b95-60637e7e645f.png">

将控制台输出的 sourceId 作如下配置即可：

```
local INPUT_CHINESE = 'com.sogou.inputmethod.sogou.pinyin'
```

至于你截图中获取 sourceId 的方法为什么和控制台输入命令返回的 sourceId 不同，这一点我也不太清楚，我是一直按照 Hammerspoon 官方文档的提供的说明来获取的，Hammespoon 相关 api 说明为：[http://www.hammerspoon.org/docs/hs.keycodes.html#currentSourceID](http://www.hammerspoon.org/docs/hs.keycodes.html#currentSourceID)

**Comment by evi1hack** [comment]
@KURANADO2 
谢谢你的解答，通过你提供的这种方式已经成功了。👍👍
