### ISSUE TITLE
请问这是什么原因呢

### ISSUE THREAD

**Issue by kyoonart** [KURANADO2/hammerspoon-kuranado#14]
<img width="510" alt="image" src="https://user-images.githubusercontent.com/49586985/181218210-8b4b6f49-6ab4-4cbf-91ce-b2eaa67ecaea.png">

**Comment by kyoonart** [comment]
<img width="510" alt="image" src="https://user-images.githubusercontent.com/49586985/181218401-0aff7649-e91f-46f3-ab3c-a88c1c8a5e44.png">

**Comment by KURANADO2** [comment]
@kyoonart k这份日志有什么问题吗，这是正常日志

**Comment by KURANADO2** [comment]
@kyoonart 可以点一下 Reload config 按钮试下还会出现这个错误吗

**Comment by kyoonart** [comment]
会出现的

**Comment by kyoonart** [comment]
@KURANADO2  会出现的

**Comment by kyoonart** [comment]
解决了 谢谢~
