### ISSUE TITLE
快捷键打开应用问题

### ISSUE THREAD

**Issue by kyoonart** [KURANADO2/hammerspoon-kuranado#15]
如果打开一个应用  然后使用 command + w 关闭了应用在当前窗口 那么再次打开应用需要按两次快捷键 请问这如何解决呢

**Comment by kyoonart** [comment]
`function toggle_app(name)
  focused = hs.window.focusedWindow()
  if focused then
    app = focused:application()
    if app:title() == name then
      app:hide()
      return
    end
  end
  hs.application.launchOrFocus(name)
end`

我写了这样一个方法 可以解决 作者看看

**Comment by KURANADO2** [comment]
这里是一个 Bug，可通过修改 modules/application.lua 文件中的下面这行代码：

```lua
frontMostApp:hide()
```

为：

```lua
hs.application.launchOrFocusByBundleID(appBundleID)
```

来解决

目前并没有修改提交，因为除此之外，application.lua 文件还有其他 Bug，我想最近几天会一起修改掉后提交

你给的代码应该是没有问题的，感谢提供！
