### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by jackytang** [KURANADO2/hammerspoon-kuranado#2]
提个建议, 可以把application和windows这两个里面的快捷键定义一个变量, 改起来也方便, 我自己改了没有给你pr,

**Comment by KURANADO2** [comment]
很好的建议，这个之前我有考虑到，最近忙于工作没时间修改
我的想法是把所有用户会修改的东西全部抽取出配置文件，这些配置文件应加入到 .gitignore 文件中，这样之后我更新模块代码后，用户拉取代码不会有任何代码冲突

**Comment by KURANADO2** [comment]
此功能已实现，增加了 modules/shortcut.lua.example 文件
- 此前用户若自行修改了快捷键，则自动更新后会产生冲突，此种情况请这部分用户备份配置后按照 README 中说明执行 install.sh 重新安装本工程，然后在 modules/shortcut.lua 文件中重新自定义快捷键
- 另一部分用户未修改任何快捷键，自动更新后并不会产生冲突，对于这部分用户有两种选择：
    1. 不用重新安装，日后如果有自定义快捷键的需求，请执行 cp modules/shortcut.lua.example modules/shortcut.lua，然后在 modules/shortcut.lua 文件中自定义快捷键
    2. 按照 README 中说明执行 install.sh 重新安装本工程，然后在 modules/shortcut.lua 文件中自定义快捷键
