### ISSUE TITLE
如何隐藏图标

### ISSUE THREAD

**Issue by oldqin97** [KURANADO2/hammerspoon-kuranado#21]
<img width="49" alt="image" src="https://user-images.githubusercontent.com/48620148/202319276-63eb7d1c-2a37-4326-8bc4-ed267d1fb1b8.png">

**Comment by KURANADO2** [comment]
这个可以借助其他软件，参考：https://www.zhihu.com/question/20100143

**Comment by oldqin97** [comment]
好的，谢谢
