### ISSUE TITLE
同一工作空间下的所有窗口自动网格式布局 响应有点慢

### ISSUE THREAD

**Issue by fbion** [KURANADO2/hammerspoon-kuranado#27]
有办法改善吗
不如同一应用快

⌃ ⌥ X | 同一工作空间下的所有窗口自动网格式布局（什么是 工作空间？？）

**Comment by KURANADO2** [comment]
![image](https://github.com/KURANADO2/hammerspoon-kuranado/assets/20608930/06b39225-9b6c-46b1-81f6-2e9de2b510a5)

工作空间即为桌面（可以通过 Ctrl + ↑ 看到当前桌面），关于工作空间的介绍：http://www.hammerspoon.org/docs/hs.spaces.html#windowsForSpace

至于性能问题，由于 local windows = hs.spaces.windowsForSpace(spaceId) 返回的 window 中包含大量 nil window（hs.window.get(windowId) 返回为 nil），导致性能较差
优化方案可以使用：local windows = hs.window.filter.windowInCurrentSpace:getWindows() 来获取 window，其中不包含 nil window，但是 windowInCurrentSpace 中的 space 指的是当前所有可见桌面的所有窗口，比如笔记本外接了一台显示器，那这里的 space 就是指笔记本屏幕上的所有窗口和外接显示器的所有窗口，也就是两个桌面上的所有窗口
