### ISSUE TITLE
Intellij -> how is your setup

### ISSUE THREAD

**Issue by muescha** [KURANADO2/hammerspoon-kuranado#28]
I see you use IntelliJ

How is your setup?
Which plugins you use?

**Comment by KURANADO2** [comment]
There are many plugins I use, such as the following:
- FindBugs-IDEA
- Free MyBatis plugin
- MyBatis Log Plugin
- Lombok
- Grep Console
- Statistic
- GsonFormat
- Easy Code
- Leetcode Editor
- CamelCase
- IdeaVim
- IdeaVimExtension
- IdeaVim-EasyMotion
- AceJump
- SequenceDiagram
- Easy JavaDoc
- SonarLint
- GitToolBox
- RestfulTool
- EasyYapi

**Comment by muescha** [comment]
thanks a lot 

But you have no special setup / plugins for LUA and for writing and debugging the hammerspoon scripts?

**Comment by KURANADO2** [comment]
I use terminal vim to write lua scripts for hammerspoon(my vim config file is [here:](https://github.com/KURANADO2/neovim-config), The Intellij Idea is only used to write java code.
If you want to write lua scripts in Intellij Idea, you can install the `EmmyLua` plugin.

**Comment by muescha** [comment]
Thanks!

I found the `Luanalysis` plugin to be slightly better than `EmmyLua`. It allowed me to have a debug mode, but both have their drawbacks when combined with Hammerspoon.

I also gave `SumnekoLua` a try, but it wasn't perfect either, so I switched back to `Luanalysis`.
