### ISSUE TITLE
解决偶现 emoji.lua:5: attempt to index a nil value 问题

### ISSUE THREAD

**Issue by KURANADO2** [KURANADO2/hammerspoon-kuranado#4]
详细异常信息：
2022-03-26 13:49:19: *** ERROR: /Users/jing/.hammerspoon/modules/emoji.lua:5: attempt to index a nil value
stack traceback:
	/Users/jing/.hammerspoon/modules/emoji.lua:5: in main chunk
	[C]: in function 'rawrequire'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: in function 'require'
	/Users/jing/.hammerspoon/modules/menu.lua:42: in function 'renderMenubar'
	/Users/jing/.hammerspoon/modules/menu.lua:66: in main chunk
	[C]: in function 'rawrequire'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: in function 'require'
	/Users/jing/.hammerspoon/init.lua:1: in main chunk
	[C]: in function 'xpcall'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:723: in function 'hs._coresetup.setup'
	(...tail calls...)

**Comment by evi1hack** [comment]
系统环境：OS: macOS 12.4  x86_64

报错信息：
```shell
2022-06-25 19:30:00: *** ERROR: /Users/xxxxxx/.hammerspoon/modules/emoji.lua:6: attempt to index a nil value
stack traceback:
	/Users/xxxxx/.hammerspoon/modules/emoji.lua:6: in main chunk
	[C]: in function 'rawrequire'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: in function 'require'
	/Users/xxxxx/.hammerspoon/modules/menu.lua:42: in function 'renderMenubar'
	/Users/xxxxx/.hammerspoon/modules/menu.lua:66: in main chunk
	[C]: in function 'rawrequire'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: in function 'require'
	/Users/xxxxxx/.hammerspoon/init.lua:1: in main chunk
	[C]: in function 'xpcall'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:723: in function 'hs._coresetup.setup'
	(...tail calls...)
```

美女这个问题修了吗？ 现在不能reload config，报 error。

**Comment by KURANADO2** [comment]
该问题暂时没有去分析
手动点击 Reload config 按钮应该是可以临时解决这个问题的

**Comment by evi1hack** [comment]
> 该问题暂时没有去分析 手动点击 Reload config 按钮应该是可以临时解决这个问题的

是的，手动 Reload config 需要多点击几次，是可以成功的，谢谢😀

**Comment by KURANADO2** [comment]
已修复
